apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-backend
  labels:
    app: {{ .Values.appName }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.backend.service.port }}
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ .Values.backend.service.port}}
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ .Values.backend.service.port}}
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 3
        env:
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
        - name: FLASK_APP
          value: "app.py"
        - name: POSTGRES_DB
          value: "{{ .Values.postgres.env.db }}"
        - name: POSTGRES_USER
          value: "{{ .Values.postgres.env.user }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.postgres.env.password }}"
        - name: POSTGRES_HOST
          value: "{{ .Values.appName }}-postgres"
        - name: DB_PORT
          value: "{{ .Values.postgres.service.port }}"
        - name: JWT_KEY
          value: "{{ .Values.backend.env.jwtKey }}"
        - name: APP_PORT
          value: "{{ .Values.backend.service.port }}"
        - name: APP_HOST
          value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}-backend
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}-backend
{{/*    tier: backend*/}}
  ports:
  - protocol: TCP
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}