apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-backend
  labels:
    app: {{ .Values.appName }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command: [ 'sh', '-c', "until nc -z -v -w30 $(POSTGRES_HOST) $(DB_PORT); do echo 'Waiting for database connection...'; sleep 2; done" ]
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.appName }}-config
                  key: postgres-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.appName }}-config
                  key: postgres-port
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.backend.service.port }}
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ .Values.backend.service.port}}
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ .Values.backend.service.port}}
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 3
        env:
        - name: FLASK_RUN_HOST
          valueFrom:
            configMapKeyRef:
              key: app-host
              name: {{.Values.appName}}-config
        - name: FLASK_APP
          value: "app.py"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: {{.Values.appName}}-secrets
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.appName }}-config
              key: postgres-db
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.appName }}-config
              key: postgres-user
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.appName }}-config
              key: postgres-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.appName }}-config
              key: postgres-port
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              key: jwt-key
              name: {{.Values.appName}}-secrets
        - name: APP_PORT
          value: "{{ .Values.backend.service.port }}"
        - name: APP_HOST
          value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}-backend
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}-backend
{{/*    tier: backend*/}}
  ports:
  - protocol: TCP
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}