apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-frontend
  labels:
    app: {{ .Values.appName }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.frontend.service.port }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.frontend.service.port}}
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: {{ .Values.frontend.service.port}}
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
        env:
        - name: BACKEND_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: backend-hostname
              name: {{.Values.appName}}-config
        - name: BACKEND_PORT
          valueFrom:
            configMapKeyRef:
              key: backend-port
              name: {{.Values.appName}}-config
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: flask-secret-key
              name: {{.Values.appName}}-secrets
        - name: APP_PORT
          value: "{{ .Values.frontend.service.port }}"
        - name: APP_HOST
          valueFrom:
            configMapKeyRef:
              key: app-host
              name: {{.Values.appName}}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}-frontend
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}-frontend
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.service.port }} 
    targetPort: {{ .Values.frontend.service.port }}