apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  postgres-password: "{{ .Values.postgres.env.password }}"
  jwt-key: "{{ .Values.backend.env.jwtKey }}"
  flask-secret-key: "{{ .Values.frontend.env.secretKey }}"